name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://collinson.pactflow.io
  PACT_BROKER_TOKEN: ZACb50bYGTlMPUis1dJpNA
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    name: "Build and Test (dotnet)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
        pact_provider:
          [
            'pactflow-provider-dotnet'
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: test for ${{ matrix.pact_provider }}
        run: GIT_BRANCH=${GITHUB_REF:11} make test
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}
      - name: Publish pacts for ${{ matrix.pact_provider }}
        run: GIT_BRANCH=${GITHUB_REF:11} make publish_pacts
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}